# Basic Visualization Workflow Tests for napari-mcp
# These tests evaluate basic visualization techniques and layer management
# Focus: Colormaps, blending modes, opacity, contrast, and basic layer operations

# Test 1: Multi-channel Overlay with Colormaps
- vars:
    question: |
      Load the first image "D:/Development/napari-mcp/eval/data/SNAP_IgM_BCR_Cell_1/input/SNAP_IgM_BCR_Cell_1_ch0_t14.tif" and then load the second image "D:/Development/napari-mcp/eval/data/SNAP_IgM_BCR_Cell_1/input/SNAP_IgM_BCR_Cell_1_ch1_t14.tif".
      Set the first channel to green colormap and the second channel to magenta colormap.
      Use additive blending for both channels to create an overlay visualization.
      Take a screenshot of the result.
      Respond with <1> if both channels are visible with their respective colors in the overlay, or <0> if it failed. Only respond with <1> or <0>.
  assert:
    - type: contains-all
      value: "<1>"
    - type: not-contains
      value: "<0>"
  options:
    cache: false
    runSerially: true

# Test 2: Colormap Variety and Selection
- vars:
    question: |
      Apply different colormaps to each channel: set channel 0 to 'viridis' and channel 1 to 'plasma'.
      Then change channel 0 to 'hot' and channel 1 to 'cool'.
      Take screenshots showing both colormap combinations.
      Respond with <1> if you successfully applied different colormaps to each channel, or <0> if it failed. Only respond with <1> or <0>.
  assert:
    - type: contains-all
      value: "<1>"
    - type: not-contains
      value: "<0>"
  options:
    cache: false
    runSerially: true

# Test 3: Contrast and Gamma Adjustment
- vars:
    question: |
      Auto-adjust contrast for both channels using auto_contrast.
      Then manually fine-tune the contrast limits: set channel 0 to [0.1, 0.9] and channel 1 to [0.2, 0.8].
      Adjust gamma correction to 1.2 for channel 0 and 0.8 for channel 1.
      Take a screenshot showing the enhanced visualization.
      Respond with <1> if the contrast and gamma adjustments were successful, or <0> if it failed. Only respond with <1> or <0>.
  assert:
    - type: contains-all
      value: "<1>"
    - type: not-contains
      value: "<0>"
  options:
    cache: false
    runSerially: true

# Test 4: Blending Mode Variations
- vars:
    question: |
      Test different blending modes: set channel 0 to 'opaque', channel 1 to 'translucent'.
      Take a screenshot to show this combination.
      Change to: channel 0 to 'additive', channel 1 to 'minimum'.
      Take a screenshot to show this combination.
      Respond with <1> if you successfully tested different blending modes, or <0> if it failed. Only respond with <1> or <0>.
  assert:
    - type: contains-all
      value: "<1>"
    - type: not-contains
      value: "<0>"
  options:
    cache: false
    runSerially: true

# Test 5: Layer Opacity and Visibility Management
- vars:
    question: |
      Set the opacity of channel 0 to 0.3 and channel 1 to 0.7.
      Take a screenshot showing the different opacities.
      Toggle the visibility of channel 0 to hide it, then show it again.
      Take screenshots showing the visibility changes.
      Respond with <1> if the opacity and visibility management was successful, or <0> if it failed. Only respond with <1> or <0>.
  assert:
    - type: contains-all
      value: "<1>"
    - type: not-contains
      value: "<0>"
  options:
    cache: false
    runSerially: true

# Test 6: Interpolation and Rendering Quality
- vars:
    question: |
      Set interpolation to 'nearest' for channel 0 and 'linear' for channel 1.
      Take a screenshot showing the different interpolation modes.
      Change channel 0 to 'cubic' interpolation.
      Take a screenshot showing the cubic interpolation.
      Respond with <1> if you successfully tested different interpolation modes, or <0> if it failed. Only respond with <1> or <0>.
  assert:
    - type: contains-all
      value: "<1>"
    - type: not-contains
      value: "<0>"
  options:
    cache: false
    runSerially: true

# Test 7: Scale Bar and Display Elements
- vars:
    question: |
      Show the scale bar with unit 'um' for the visualization.
      Take a screenshot showing the scale bar.
      Hide the scale bar, then show it again with unit 'nm'.
      Take a screenshot showing the scale bar with different units.
      Respond with <1> if the scale bar management was successful, or <0> if it failed. Only respond with <1> or <0>.
  assert:
    - type: contains-all
      value: "<1>"
    - type: not-contains
      value: "<0>"
  options:
    cache: false
    runSerially: true

# Test 8: Cleanup - Reset for next test run
- vars:
    question: |
      Delete all loaded layers and reset the view to 2D mode to prepare for the next test run.
      Respond with <1> if all layers were successfully deleted and the view was reset, or <0> if it failed. Only respond with <1> or <0>.
  assert:
    - type: contains-all
      value: "<1>"
    - type: not-contains
      value: "<0>"
  options:
    cache: false
    runSerially: true
